base.url=https://www.saucedemo.com/
inventory.url = https://www.saucedemo.com/inventory.html
valid.username=standard_user
valid.password=secret_sauce
invalid.password=sai_mat_khau_123
sql.injection.payload= ' OR '1'='1
locked.username=locked_out_user
checkout.firstname=Apple
checkout.lastname=Bee
checkout.zipcode=123
xss.injection.payload=<script>alert('XSS')</script>